openapi: 3.1.0
info:
  title: API de Tareas con Autenticación
  version: 1.0.0
  description: API para gestionar tareas con autenticación y autorización basada en roles.

servers:
  - url: http://localhost:3000
    description: Servidor local

paths:
  /api/login:
    post:
      summary: Iniciar sesión
      description: Inicia sesión con correo electrónico y contraseña para obtener un token JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - correo
                - contrasenia
              properties:
                correo:
                  type: string
                  format: email
                  description: Correo electrónico del usuario
                  example: example@example.com
                contrasenia:
                  type: string
                  description: Contraseña del usuario
                  example: yourpassword
      responses:
        "200":
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de éxito
                    example: Inicio de sesión exitoso
                  data:
                    type: object
                    description: Datos del usuario y token JWT
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        "400":
          description: Solicitud incorrecta
        "500":
          description: Error del servidor

  /api/registrar:
    post:
      summary: Registrar usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - correo
                - contrasenia
              properties:
                correo:
                  type: string
                  format: email
                  example: example@example.com
                contrasenia:
                  type: string
                  example: yourpassword
      responses:
        "200":
          description: Registro exitoso
        "500":
          description: Error del servidor

  /api/logout:
    post:
      summary: Cerrar sesión
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Sesión cerrada correctamente
        "500":
          description: Error del servidor
  /api/libros:
    get:
      summary: Obtener todos los libros
      description: Devuelve una lista de todos los libros registrados en el sistema.
      security:
        - bearerAuth: []  # Si requiere autenticación con JWT
      responses:
        "200":
          description: Lista de libros obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    titulo:
                      type: string
                      example: "Cien años de soledad"
                    autor:
                      type: string
                      example: "Gabriel García Márquez"
                    publicado:
                      type: string
                      format: date
                      example: "1967-05-30"
        "401":
          description: No autorizado - token inválido o ausente
        "500":
          description: Error interno del servidor

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT