openapi: 3.0.0
info:
  title: API Backend
  version: 1.0.0
  description: API para gestión de usuarios y tareas

paths:
  /api/registrar:
    post:
      summary: Registrar usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: Usuario registrado correctamente
        '500':
          description: Error del servidor

  /api/login:
    post:
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login exitoso
        '500':
          description: Error del servidor

  /api/tareas:
    get:
      summary: Obtener tareas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Tareas obtenidas correctamente
        '401':
          description: Token no válido

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
